# Generated by Django 2.2.8 on 2020-06-23 13:30

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adset_updte_hours',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('access_token', models.CharField(max_length=1000)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('targeting', jsonfield.fields.JSONField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='adset',
            name='targeting',
            field=jsonfield.fields.JSONField(max_length=200),
        ),
        migrations.AlterField(
            model_name='adsetorignal',
            name='targeting',
            field=jsonfield.fields.JSONField(max_length=200),
        ),
    ]
